### ISSUE TITLE
Version Android

### ISSUE THREAD

**Issue by fazti** [seatsio/seatsio-android#1]
Is it possible for this library to work on version 5.0 of Android? Can you help?

**Comment by bverbeken** [comment]
Hi, 

Thanks for the question. 
We discussed this on the support channel, but I wanted to repeat here for clarity. It's not possible to downgrade the minimal required Android version, because seatsio-android uses functional interfaces in its public API, and Android SDK version 24 is the lowest version to support those. 

So the only option to support lower android versions is to fork seatsio-android. 

Thanks,
Ben
